version: '3'
services:
  webserver:
    build:
      context: ./nginx
    ports:
      - 83:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./web/:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork
  php:
    build:
      context: ./php
    volumes:
      - ./web/:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
